-- TABLE : ETUDIANTS
CREATE TABLE ETUDIANTS (
    ID_ETUDIANT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_ETUDIANT VARCHAR(100) NOT NULL,
    ID_MODE_PAIEMENT INT,
    FOREIGN KEY (ID_MODE_PAIEMENT) REFERENCES MODE_PAIEMENT(ID_MODE_PAIEMENT)
);

-- TABLE : MODE_PAIEMENT
CREATE TABLE MODE_PAIEMENT (
    ID_MODE_PAIEMENT INT AUTO_INCREMENT PRIMARY KEY,
    NOM_MODE VARCHAR(50) NOT NULL,
    NBRMOIS INT NOT NULL
);

-- TABLE : ECOLAGE
CREATE TABLE ECOLAGE (
    ID_ECOLAGE INT AUTO_INCREMENT PRIMARY KEY,
    ID_ETUDIANT INT NOT NULL,
    MONTANT INT NOT NULL,
    ID_ANNEE INT NOT NULL,
    FOREIGN KEY (ID_ETUDIANT) REFERENCES ETUDIANTS(ID_ETUDIANT),
    FOREIGN KEY (ID_ANNEE) REFERENCES ANNEE(ID_ANNEE)
);

-- TABLE : ANNEE
CREATE TABLE ANNEE (
    ID_ANNEE INT AUTO_INCREMENT PRIMARY KEY,
    ANNEE_DEBUT INT NOT NULL,
    ANNEE_FIN INT NOT NULL,
    MONTANT INT NOT NULL,
    CONSTRAINT CHK_ANNEE CHECK (ANNEE_FIN > ANNEE_DEBUT)
);
