-- TABLE : MATIERES
CREATE TABLE MATIERES (
    ID_MATIERE INT PRIMARY KEY,
    NOM_MATIERE VARCHAR2(100) NOT NULL,
    CREDITS INT
);

-- TABLE : NOTES
CREATE TABLE NOTES (
    ID_NOTE INT PRIMARY KEY,
    ID_ETUDIANT INT NOT NULL,
    ID_MATIERE INT NOT NULL, 
    SEMESTRE INT CHECK (SEMESTRE IN (1, 2)),
    NOTE FLOAT CHECK (NOTE BETWEEN 0 AND 20),
    ID_ANNEE INT NOT NULL,
    FOREIGN KEY (ID_MATIERE) REFERENCES MATIERES(ID_MATIERE)
);


